### ISSUE TITLE
Plan de calidad PC BOX

### ISSUE THREAD

**Issue by MaGuadalupeQuiroz** [SistemasTecTlaxiaco/practica-de-calidad-entrevista-gestion-de-proyecto#1]
[PRACTICA DE CALIDAD PC BOX.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-calidad-entrevista-gestion-de-proyecto/files/7322708/PRACTICA.DE.CALIDAD.PC.BOX.pdf)

**Comment by dulce-blm** [comment]
Calificación: 20 puntos

**Comment by josealfredo79** [comment]
Bien hecho y revisado
